// flow-typed signature: 94a1692c2413b2053e61f773c385ca20
// flow-typed version: <<STUB>>/babel-plugin-source-map-support_v^1.0.0/flow_v0.75.0

/**
 * This is an autogenerated libdef stub for:
 *
 *   'babel-plugin-source-map-support'
 *
 * Fill this stub out by replacing all the `any` types.
 *
 * Once filled out, we encourage you to share your work with the
 * community by sending a pull request to:
 * https://github.com/flowtype/flow-typed
 */

declare module 'babel-plugin-source-map-support' {
  declare module.exports: any;
}

/**
 * We include stubs for each file inside this npm package in case you need to
 * require those files directly. Feel free to delete any files that aren't
 * needed.
 */
declare module 'babel-plugin-source-map-support/dist/plugin' {
  declare module.exports: any;
}

// Filename aliases
declare module 'babel-plugin-source-map-support/dist/plugin.js' {
  declare module.exports: $Exports<'babel-plugin-source-map-support/dist/plugin'>;
}
