// flow-typed signature: dccb5346fd0910772860a2544d8b1337
// flow-typed version: <<STUB>>/middy_v^0.15.7/flow_v0.75.0

/**
 * This is an autogenerated libdef stub for:
 *
 *   'middy'
 *
 * Fill this stub out by replacing all the `any` types.
 *
 * Once filled out, we encourage you to share your work with the
 * community by sending a pull request to:
 * https://github.com/flowtype/flow-typed
 */

declare module 'middy' {
  declare module.exports: any;
}

/**
 * We include stubs for each file inside this npm package in case you need to
 * require those files directly. Feel free to delete any files that aren't
 * needed.
 */
declare module 'middy/middlewares' {
  declare module.exports: any;
}

declare module 'middy/src/__tests__/isPromise' {
  declare module.exports: any;
}

declare module 'middy/src/__tests__/middy' {
  declare module.exports: any;
}

declare module 'middy/src/isPromise' {
  declare module.exports: any;
}

declare module 'middy/src/middlewares/__tests__/cache' {
  declare module.exports: any;
}

declare module 'middy/src/middlewares/__tests__/cors' {
  declare module.exports: any;
}

declare module 'middy/src/middlewares/__tests__/doNotWaitForEmptyEventLoop' {
  declare module.exports: any;
}

declare module 'middy/src/middlewares/__tests__/httpContentNegotiation' {
  declare module.exports: any;
}

declare module 'middy/src/middlewares/__tests__/httpErrorHandler' {
  declare module.exports: any;
}

declare module 'middy/src/middlewares/__tests__/httpEventNormalizer' {
  declare module.exports: any;
}

declare module 'middy/src/middlewares/__tests__/httpHeaderNormalizer' {
  declare module.exports: any;
}

declare module 'middy/src/middlewares/__tests__/httpPartialResponse' {
  declare module.exports: any;
}

declare module 'middy/src/middlewares/__tests__/index' {
  declare module.exports: any;
}

declare module 'middy/src/middlewares/__tests__/jsonBodyParser' {
  declare module.exports: any;
}

declare module 'middy/src/middlewares/__tests__/s3KeyNormalizer' {
  declare module.exports: any;
}

declare module 'middy/src/middlewares/__tests__/ssm' {
  declare module.exports: any;
}

declare module 'middy/src/middlewares/__tests__/urlencodeBodyParser' {
  declare module.exports: any;
}

declare module 'middy/src/middlewares/__tests__/validator' {
  declare module.exports: any;
}

declare module 'middy/src/middlewares/__tests__/warmup' {
  declare module.exports: any;
}

declare module 'middy/src/middlewares/cache' {
  declare module.exports: any;
}

declare module 'middy/src/middlewares/cors' {
  declare module.exports: any;
}

declare module 'middy/src/middlewares/doNotWaitForEmptyEventLoop' {
  declare module.exports: any;
}

declare module 'middy/src/middlewares/httpContentNegotiation' {
  declare module.exports: any;
}

declare module 'middy/src/middlewares/httpErrorHandler' {
  declare module.exports: any;
}

declare module 'middy/src/middlewares/httpEventNormalizer' {
  declare module.exports: any;
}

declare module 'middy/src/middlewares/httpHeaderNormalizer' {
  declare module.exports: any;
}

declare module 'middy/src/middlewares/httpPartialResponse' {
  declare module.exports: any;
}

declare module 'middy/src/middlewares/index' {
  declare module.exports: any;
}

declare module 'middy/src/middlewares/jsonBodyParser' {
  declare module.exports: any;
}

declare module 'middy/src/middlewares/s3KeyNormalizer' {
  declare module.exports: any;
}

declare module 'middy/src/middlewares/ssm' {
  declare module.exports: any;
}

declare module 'middy/src/middlewares/urlEncodeBodyParser' {
  declare module.exports: any;
}

declare module 'middy/src/middlewares/validator' {
  declare module.exports: any;
}

declare module 'middy/src/middlewares/warmup' {
  declare module.exports: any;
}

declare module 'middy/src/middy' {
  declare module.exports: any;
}

// Filename aliases
declare module 'middy/index' {
  declare module.exports: $Exports<'middy'>;
}
declare module 'middy/index.js' {
  declare module.exports: $Exports<'middy'>;
}
declare module 'middy/middlewares.js' {
  declare module.exports: $Exports<'middy/middlewares'>;
}
declare module 'middy/src/__tests__/isPromise.js' {
  declare module.exports: $Exports<'middy/src/__tests__/isPromise'>;
}
declare module 'middy/src/__tests__/middy.js' {
  declare module.exports: $Exports<'middy/src/__tests__/middy'>;
}
declare module 'middy/src/isPromise.js' {
  declare module.exports: $Exports<'middy/src/isPromise'>;
}
declare module 'middy/src/middlewares/__tests__/cache.js' {
  declare module.exports: $Exports<'middy/src/middlewares/__tests__/cache'>;
}
declare module 'middy/src/middlewares/__tests__/cors.js' {
  declare module.exports: $Exports<'middy/src/middlewares/__tests__/cors'>;
}
declare module 'middy/src/middlewares/__tests__/doNotWaitForEmptyEventLoop.js' {
  declare module.exports: $Exports<'middy/src/middlewares/__tests__/doNotWaitForEmptyEventLoop'>;
}
declare module 'middy/src/middlewares/__tests__/httpContentNegotiation.js' {
  declare module.exports: $Exports<'middy/src/middlewares/__tests__/httpContentNegotiation'>;
}
declare module 'middy/src/middlewares/__tests__/httpErrorHandler.js' {
  declare module.exports: $Exports<'middy/src/middlewares/__tests__/httpErrorHandler'>;
}
declare module 'middy/src/middlewares/__tests__/httpEventNormalizer.js' {
  declare module.exports: $Exports<'middy/src/middlewares/__tests__/httpEventNormalizer'>;
}
declare module 'middy/src/middlewares/__tests__/httpHeaderNormalizer.js' {
  declare module.exports: $Exports<'middy/src/middlewares/__tests__/httpHeaderNormalizer'>;
}
declare module 'middy/src/middlewares/__tests__/httpPartialResponse.js' {
  declare module.exports: $Exports<'middy/src/middlewares/__tests__/httpPartialResponse'>;
}
declare module 'middy/src/middlewares/__tests__/index.js' {
  declare module.exports: $Exports<'middy/src/middlewares/__tests__/index'>;
}
declare module 'middy/src/middlewares/__tests__/jsonBodyParser.js' {
  declare module.exports: $Exports<'middy/src/middlewares/__tests__/jsonBodyParser'>;
}
declare module 'middy/src/middlewares/__tests__/s3KeyNormalizer.js' {
  declare module.exports: $Exports<'middy/src/middlewares/__tests__/s3KeyNormalizer'>;
}
declare module 'middy/src/middlewares/__tests__/ssm.js' {
  declare module.exports: $Exports<'middy/src/middlewares/__tests__/ssm'>;
}
declare module 'middy/src/middlewares/__tests__/urlencodeBodyParser.js' {
  declare module.exports: $Exports<'middy/src/middlewares/__tests__/urlencodeBodyParser'>;
}
declare module 'middy/src/middlewares/__tests__/validator.js' {
  declare module.exports: $Exports<'middy/src/middlewares/__tests__/validator'>;
}
declare module 'middy/src/middlewares/__tests__/warmup.js' {
  declare module.exports: $Exports<'middy/src/middlewares/__tests__/warmup'>;
}
declare module 'middy/src/middlewares/cache.js' {
  declare module.exports: $Exports<'middy/src/middlewares/cache'>;
}
declare module 'middy/src/middlewares/cors.js' {
  declare module.exports: $Exports<'middy/src/middlewares/cors'>;
}
declare module 'middy/src/middlewares/doNotWaitForEmptyEventLoop.js' {
  declare module.exports: $Exports<'middy/src/middlewares/doNotWaitForEmptyEventLoop'>;
}
declare module 'middy/src/middlewares/httpContentNegotiation.js' {
  declare module.exports: $Exports<'middy/src/middlewares/httpContentNegotiation'>;
}
declare module 'middy/src/middlewares/httpErrorHandler.js' {
  declare module.exports: $Exports<'middy/src/middlewares/httpErrorHandler'>;
}
declare module 'middy/src/middlewares/httpEventNormalizer.js' {
  declare module.exports: $Exports<'middy/src/middlewares/httpEventNormalizer'>;
}
declare module 'middy/src/middlewares/httpHeaderNormalizer.js' {
  declare module.exports: $Exports<'middy/src/middlewares/httpHeaderNormalizer'>;
}
declare module 'middy/src/middlewares/httpPartialResponse.js' {
  declare module.exports: $Exports<'middy/src/middlewares/httpPartialResponse'>;
}
declare module 'middy/src/middlewares/index.js' {
  declare module.exports: $Exports<'middy/src/middlewares/index'>;
}
declare module 'middy/src/middlewares/jsonBodyParser.js' {
  declare module.exports: $Exports<'middy/src/middlewares/jsonBodyParser'>;
}
declare module 'middy/src/middlewares/s3KeyNormalizer.js' {
  declare module.exports: $Exports<'middy/src/middlewares/s3KeyNormalizer'>;
}
declare module 'middy/src/middlewares/ssm.js' {
  declare module.exports: $Exports<'middy/src/middlewares/ssm'>;
}
declare module 'middy/src/middlewares/urlEncodeBodyParser.js' {
  declare module.exports: $Exports<'middy/src/middlewares/urlEncodeBodyParser'>;
}
declare module 'middy/src/middlewares/validator.js' {
  declare module.exports: $Exports<'middy/src/middlewares/validator'>;
}
declare module 'middy/src/middlewares/warmup.js' {
  declare module.exports: $Exports<'middy/src/middlewares/warmup'>;
}
declare module 'middy/src/middy.js' {
  declare module.exports: $Exports<'middy/src/middy'>;
}
